//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace DroneLibrary
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.simplysim.net/2010/06/droneconfig.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.simplysim.net/2010/06/droneconfig.xsd", IsNullable = false)]
    public partial class DroneConfig
    {

        private RotorDesc[] rotorsField;

        private string bodyNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Rotor", IsNullable = false)]
        public RotorDesc[] Rotors
        {
            get
            {
                return this.rotorsField;
            }
            set
            {
                this.rotorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BodyName
        {
            get
            {
                return this.bodyNameField;
            }
            set
            {
                this.bodyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.simplysim.net/2010/06/droneconfig.xsd")]
    public partial class RotorDesc
    {

        private RotorDescEngine engineField;

        private RotorDescBlade bladeField;

        private string nameField;

        private float massLiftField;

        private float rPMLiftField;

        /// <remarks/>
        public RotorDescEngine Engine
        {
            get
            {
                return this.engineField;
            }
            set
            {
                this.engineField = value;
            }
        }

        /// <remarks/>
        public RotorDescBlade Blade
        {
            get
            {
                return this.bladeField;
            }
            set
            {
                this.bladeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float MassLift
        {
            get
            {
                return this.massLiftField;
            }
            set
            {
                this.massLiftField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float RPMLift
        {
            get
            {
                return this.rPMLiftField;
            }
            set
            {
                this.rPMLiftField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.simplysim.net/2010/06/droneconfig.xsd")]
    public partial class RotorDescEngine
    {

        private string nameField;

        private Polarity polarityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Polarity Polarity
        {
            get
            {
                return this.polarityField;
            }
            set
            {
                this.polarityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.simplysim.net/2010/06/droneconfig.xsd")]
    public enum Polarity
    {

        /// <remarks/>
        Positive,

        /// <remarks/>
        Negative,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.simplysim.net/2010/06/droneconfig.xsd")]
    public partial class RotorDescBlade
    {

        private string nameField;

        private BladeType typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BladeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.simplysim.net/2010/06/droneconfig.xsd")]
    public enum BladeType
    {

        /// <remarks/>
        RightHandedBlade,

        /// <remarks/>
        LeftHandedBlade,
    }
}
